reshape((0axis, 1axis, 2axis): tuple) : 차원들의 곱과 총원소의 개수가 일치해야 한다.
<br>
<h3>Curse of Dimension<h3/> <br>
<p1>차원이 증가하면서 학습data수가 적어지면서 모델의 성능이 저하되는 현상이다.
고차원에서 여러 차원으로 변수를 표현했기 때문에 데이터의 특성을 더 잘 나타내겠지만 1차원에서 3차원으로 갈수록 데이터들이 성기게 된다. 
저차원으로 갈수록 데이터가 더 밀집되게 되지만 데이터의 특성을 제대로 표현하지 못한다. tradeoff관계인 것이다.


<p1/>

![nn](./Curse_of_Dimension.jpg) <br>


In [2]:
import numpy as np

arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3, 4)) # 총 원소의 개수와 맞아야 한다. 3*4
print(arr, arr,ndim, sep='\n')
# 원소들이 순서대로 분할된다.

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
arr = arr.reshape((2,3,2))
print(arr)
arr = arr.reshape((2,2,1,3))
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]]


resize(0aixs:int, 1axis:int ...) : reshape과 동일한 기능이지만 원본을 변경시킨다는 차이가 있다. <br>
ravel(): 1차원 배열로 변경시킨다.<br>

In [6]:
arr = np.arange(12)
arr.resize(3, 4) #arr.resize((3, 4)) 튜플이 아니어도 된다.
print(arr)

arr = arr.ravel()
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
arr = np.arange(12)
print(arr)

arr = arr.reshape(3, -1) # 축들을 정해주고 나머지 하나에 -1을 넣으면 알아서 계산함
print(arr)
arr = arr.reshape(3,2,-1)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


expand_dims(ndarray, axis:int): 입력한 axis값를 새로 추가한다. 기존 축은 이름만 바뀜<br>
만일 axis를 입력하지 않으면 1차원 배열로 한번에 축소해버린다. <br>
squeeze(ndarray, axis:int): 한 차원씩 축소한다.<br>

In [13]:
arr = np.array([1, 2])
print(arr, arr.shape)
arr = np.expand_dims(arr, axis=1)
print(arr, arr.shape)
# 기존에 있던 axis는 이름만 바꾸고 지정한 축만 새로 추가한다.
#   (1, 2) <- (2,) -> (2,1)

[1 2] (2,)
[[1]
 [2]] (2, 1)


In [19]:
arr = np.array([[1, 2]])
print(f'original array \n{arr}\n {arr.shape} \n {arr.ndim}')
arr2 = np.squeeze(arr, axis=0)
print("axis=0 squeezed arr : \n",arr2, arr2.shape, arr2.ndim)


original array 
[[1 2]]
 (1, 2) 
 2
axis=0 squeezed arr : 
 [1 2] (2,) 1


In [25]:
arr = np.array([[[1],
                [2],
                [3]]])
print(f'arr \n {arr} \n {arr.shape} \n {arr.ndim}')
arr2 = np.squeeze(arr, axis=2)
print(f'axis=2 squeezed arr : \n {arr2} \n {arr2.shape}\n{arr2.ndim}')

arr 
 [[[1]
  [2]
  [3]]] 
 (1, 3, 1) 
 3
axis=2 squeezed arr : 
 [[1 2 3]] 
 (1, 3)
2


In [27]:
arr = np.array([[[1,2,3]]])
print(arr, arr.shape, arr.ndim) # 차원의 갯수는 한쪽 [의 갯수와 같다.
arr = np.squeeze(arr, axis=1)
print(arr, arr.shape, arr.ndim)

# axis 값을 주지 않으면 모두 1차원 배열로 축소해버린다.
arr = np.squeeze(arr)
print(arr, arr.shape, arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2
[1 2 3] (3,) 1


![nn](./Transpose_matrix.jpg) <br>

In [31]:
arr = np.array([[1,2], [3,4]])

print(arr.T)

arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(arr.T)
# 정방행렬이 아니면 축을 뒤바꿔서 전치된다.

[[1 3]
 [2 4]]
[[1 3 5]
 [2 4 6]]


In [30]:
arr = np.random.randint(1,5, size=(3,3))
# 역행렬 구하기
arr_inverse = np.linalg.inv(arr) # linear_algebra_inverse_matrix
print(arr_inverse)
print(np.dot(arr, arr_inverse)) # 검증된다.

[[-1.00000000e+00  1.00000000e+00  1.38777878e-17]
 [ 0.00000000e+00  4.00000000e-01 -2.00000000e-01]
 [ 2.00000000e+00 -2.20000000e+00  6.00000000e-01]]
[[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [33]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
arr2 = np.full((3,2), 2)
# shape을 내적할 수 잇게 바꾸어야 할 때 유용하다.
print((arr.T).dot(arr2))

[[18 18]
 [24 24]]
