배열의 연산은 기본적으로 shape이 같아야 한다.
다를 때는 broadcasting을 써야 한다.

In [6]:
import numpy as np

arr1 = np.array([range(1,4), range(4,7), range(7,10)], dtype=int)
arr2 = np.array([[2, 2, 2],[2,2,2],[2,2,2]], dtype=int)


[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [7]:
# 기본적으로 연산자 오버라이딩이 되어 있다.
arr3 = arr1 + arr2
print(arr3)
print(np.add(arr1, arr2)) # JAVA처럼 객체지향의 메스도 형식으로도 가능하다.

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
arr3 = arr1 - arr2
print(arr3)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [11]:
# 곱셈
# 주의!! 행렬곱이 아니고 원소별로 산술곱이다.

arr3= arr1 * arr2
print(arr3)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
# 나눗셈, 이 또한 원소별로 산술나눗셈이다.

arr3= arr1/arr2
print(arr3)
print(np.divide(arr1,arr2))
# int32였으나 나누면 자동으로 float로 바뀐다.
# python에선 /은 실수나눗셈인 점을 일관성 있게 유지한 것이다.

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [16]:
# 제곱
#  곱셈도 산술곱이었기 때문에 제곱도 원소 각각의 제곱이다.
print(arr1**2)
print(arr2**2)
print(np.square(arr1))

# 제곱근 square_root
print(np.sqrt(arr1))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [18]:
# 몫
print(arr1//2) # 정수나눗셈
print(arr1 // arr2)

# 나머지 modular 연산자
print(arr1 % 2)
print(arr1 % arr2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [20]:
# Dot product, 내적

#1차원
arr1 = np.array([2,3,4])
arr2 = np.array([1, 2, 3])
# (1*n) * (n * 1) = 1 그냥 스칼라 값
print(np.dot(arr1, arr2))

# 2 차원
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1,2], [0,3]])
print(np.dot(arr1, arr2))

20
[[ 1  8]
 [ 3 18]]


In [29]:
# 절댓값
arr1= np.array([[1, -2], [-4, 5]])
print(np.abs(arr1))

# 올림
arr1 = np.array([[1.9321, -2.23], [-4.32, 5.11]])
print(f'arr1 == \n{arr1}.')
print("np.ceil(arr1) == \n",np.ceil(arr1))
# 내림 : 대상값보다 작은 정수 중 가장 큰 정수, <- 0 <- 
print("np.floor(arr1) == \n", np.floor(arr1))
# 반올림
print("np.round(arr1) == \n", np.round(arr1))
# 버림: 소숫점 부분을 글자 그대로 떼어버린다,  -> 0 <- 
print("np.trunc(arr1) == \n", np.trunc(arr1))

[[1 2]
 [4 5]]
arr1 == 
[[ 1.9321 -2.23  ]
 [-4.32    5.11  ]].
np.ceil(arr1) == 
 [[ 2. -2.]
 [-4.  6.]]
np.floor(arr1) == 
 [[ 1. -3.]
 [-5.  5.]]
np.round(arr1) == 
 [[ 2. -2.]
 [-4.  5.]]
np.trunc(arr1) == 
 [[ 1. -2.]
 [-4.  5.]]


In [34]:
# min(), max() 최대최소값

arr = np.array([[1, 2, 3], [0,1,4]])
print(np.min(arr), arr.min())
print(arr.min(axis=0)) # 축 방향으로 가장 작은 값들 추출
print(arr.min(axis=1))

print(np.max(arr, axis=0), arr.max(axis=1))

0 0
[0 1 3]
[1 0]
[1 2 4] [3 4]


In [42]:
# sum 합
print(np.sum(arr), arr.sum())
print(np.sum(arr, axis=0), arr.sum(axis=1))

# mean 산술평균
print(np.mean(arr), arr.mean())
print(np.mean(arr, axis=0), arr.mean(axis=1))

# std 표준편차, var 분산
print(np.std(arr), arr.std())
print(np.std(arr, axis=0), arr.std(axis=1))

# cumsum 누적합
print(np.cumsum(arr), arr.cumsum())
print(np.cumsum(arr, axis=0), arr.cumsum(axis=1))

11 11
[1 3 7] [6 5]
1.8333333333333333 1.8333333333333333
[0.5 1.5 3.5] [2.         1.66666667]
1.343709624716425 1.343709624716425
[0.5 0.5 0.5] [0.81649658 1.69967317]
[ 1  3  6  6  7 11] [ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]] [[1 3 6]
 [0 1 5]]


In [46]:
# median 중앙값
# 원소 개수가 짝수이면 중앙에 있는 2개의 값의 중간값
print(np.median(arr))
print(np.median(arr, axis=0))
# median은 객체 메소드가 없다. arr.median() 없더라

1.5
[0.5 1.5 3.5]


In [51]:
# 비교 연산 -> boolean

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[1,0,3], [4, -2, 9]])

# <, >, ==, <=, >= 각각의 원소끼리 비교한다.
print(f'arr1 == arr2 :\n{arr1 == arr2}')
print(f'arr1 < arr2 :\n{arr1 < arr2}')

# 진짜 배열 전체로 비교해서 같은 배열인지 비교하는 방법
print(f"np.array_equal(arr1, arr2) == {np.array_equal(arr1, arr2)}")

arr1 == arr2 :
[[ True False  True]
 [ True False False]]
arr1 < arr2 :
[[False False False]
 [False False  True]]
np.array_equal(arr1, arr2) == False


In [53]:
# 삼각함수
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
# 각각의 원소들의 삼각함수 값
print(np.sin(arr1), np.cos(arr1), np.tan(arr), sep='\n') 
print(np.pi)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 0.          1.55740772  1.15782128]]
3.141592653589793


![nn](./broadcasting.jpg) <br>
![nn](./broadcasting2.jpg) <br>
shape이 안 맞던 작은 행렬을 확장해서 모양을 맞춘다.

In [56]:
# broadcasting
# case1
arr1 = np.array([[0,0,0],
                [1,1,1],
                [2,2,2]])
arr2 = np.array([5,6,7])

print(arr1 + arr2) # 2번째 행렬이 확장된다.

# case2
arr1 = np.array([[1,1,1]]) # 아래로 확장
arr2 = np.array([[0],[1],[2]]) # 옆으로 확장

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


벡터 연산의 속도 차이를 보는 파트

In [60]:
import time

arr = np.arange(99999999)
sum =0
before = time.time()
# 일반 파이썬
for i in arr:
    sum += i
after = time.time()
print(sum, after- before, "sec")

<ipython-input-60-8acf1d7737b2>:8: RuntimeWarning: overflow encountered in long_scalars
  sum += i


787459713 22.603886127471924 sec


In [61]:
# 벡터 연산
before = time.time()
sum = np.sum(arr)
after = time.time()
print(sum, after - before, "sec")
# numpy가 어마어마 하게 빠르다.

787459713 0.05001401901245117 sec


In [63]:
arr1 = np.arange(9999999)
arr2 = np.arange(9999999)
sum=0
before = time.time()
for i, j in zip(arr1, arr2):
    sum += i*j
after = time.time()
print(sum, after - before, 'sec')


<ipython-input-63-e67704ce07ba>:6: RuntimeWarning: overflow encountered in long_scalars
  sum += i*j


-1295478593 19.34899616241455 sec


In [64]:
sum=0
before = time.time()
sum = np.dot(arr1, arr2)
after = time.time()
print(sum, after - before, 'sec')

-1295478593 0.018002033233642578 sec
