np.insert(ndarray, index: int, value, axis: int | None = None) : 파이썬리스트와 동일하다. <br>

axis는 None이 디폴트이기 때문에 따로 지정하지 않으면 1차원 배열로 바뀐다.<br>

np.delete(ndarray, index: int, axis: int | None = None) : <br>
축을 기준으로 index위치 한 줄을 지워라

In [45]:
import numpy as np
arr = [1,2,3,4,5]
arr.insert(2, -1)
print(arr)

[1, 2, -1, 3, 4, 5]


In [46]:
# 1차원 배열
arr = np.arange(1,9)
arr = np.insert(arr, 2, 50)
print(arr)

# 2 차원 배열
# 입력한 축 방향으로 다중으로 값을 삽입한다.
arr = np.arange(1,13).reshape((3,4))
print(f'arr : \n {arr}')
arr2 = np.insert(arr, 2, 50, axis=0)
print(f'axis=0 inserted arr2 \n {arr2}')
arr3 = np.insert(arr, 2, 50, axis=1)
print(f'axis=1 inserted arr3 \n {arr3}')
# 배열arr에서 1 axis를 기준으로 인덱스2인 곳에 50을 추가한 새 배열을 반환하라

[ 1  2 50  3  4  5  6  7  8]
arr : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
axis=0 inserted arr2 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
axis=1 inserted arr3 
 [[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]


In [47]:
# delete
# 행렬의 한 선분을 싹 삭제한다.
arr = np.arange(1,13).reshape((3,4))
print(f'arr : \n {arr}')
arr2 = np.delete(arr, 2, axis=0)
print(f'arr2 : \n{arr2}')
print(np.delete(arr, 2)) # axis=None defualt

arr : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr2 : 
[[1 2 3 4]
 [5 6 7 8]]
[ 1  2  4  5  6  7  8  9 10 11 12]


ndarray3 = np.append(ndarray1, ndarray2) : 원래 배열 끝에 다른 배열을 붙여 새 배열을 반환한다. <br>

Python list에서 append가 원소를 원본 리스트 끝에 붙이는 것과 많이 다르다.

In [48]:
arr1 = np.arange(1, 13).reshape(3,4)
arr2 = np.arange(1,13).reshape((3,4))

# axis=0
arr3 = np.append(arr1, arr2, axis=0)
print(arr3)
print('='*100)
arr3 = np.append(arr1, arr2, axis=1)
print(arr3)
print('='*100)
arr3 = np.append(arr1, arr2) # axis=None default
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12  1  2  3  4  5  6  7  8  9 10 11 12]


np.vstack() :  axis=0을 기준으로 배열을 병합    <br>
np.hstack() :  axis=1을 기준으로 배열을 병합    <br>

In [49]:
arr1 = np.arange(1, 13).reshape(3,4)
arr2 = np.arange(1,13).reshape((3,4))


# 반드시 tuple로 넣어줘야 한다. 함수가 그렇게 설계됨
arr3 = np.vstack((arr1, arr2)) 
print(arr3)
print('='*100)
arr3 = np.hstack((arr1, arr2)) 
print(arr3)
print('='*100)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


중요! <br>
np.concatenate() : <br>
(ndarray_list: list, axis: int | None = None) -> ndarray <br>
tuple이어도 상관없다.

In [50]:
arr1 = np.arange(1, 13).reshape(3,4)
arr2 = np.arange(1,13).reshape((3,4))

arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)

[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]


배열을 축을 기준으로 분할 <br>

np.vsplit(ndarray, num: int)) : axis=0을 기준으로 분할 <br>

np.hsplit(): axis=1을 기준으로 분할        <br>


(ndarray, num: int) -> splited_ndarrays: list

In [51]:
arr1 = np.arange(1, 13).reshape(3,4)
print(arr1)
# row가 3개이므로 홀수개로만 분할할 수 있다.
arr_vsplit = np.vsplit(arr1, 3)
print(arr_vsplit)
arr_hsplit = np.hsplit(arr1, 2)
print(arr_hsplit)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


numpy에서 3차원 배열의 shape에서 이상한 점이 발견된다. <br>
2차원 배열까지는 (0axis, 1axis)로 본다. <br>
3차원 배열은 (2axis, 0axis, 1axis)처럼 보인다. 그러나 아니다. <br>
이는 마치 머신러닝에서 (batch_size 혹은 sample개수, row, column)처럼 보인다. <br>
<br>
나도 이 점이 헷갈려서 머신러닝할 때, 행렬의 형태를 맞춰주는 것이 어려웠다.<br>

(height, row, column) == (0axis, 1axis, 2axis) 

배열은 리스트의 중첩이다. <br>
축은 단지 가장 바깥 리스트에서 안쪽 리스트를 순서대로 0부터 이름 붙인 것이다. <br>
[[[1,2], [3,4]], [[5, 6], [7, 8]]] <br>
axis0: [[1, 2], [3, 4]] -> [[5, 6], [7, 8]] <br>
axis1: [1, 2] -> [3, 4], [5, 6] -> [7, 8] <br>
axis2: 1->2, 3->4, 5->6, 7->8 <br>
이런 방식으로 4차원 이상 높아져도 따져볼 수 있다. 행렬개념으론 추상적이어서 못 알기 힘들다.


![nn](./axis.png)

In [52]:
# 3차원
arr = np.random.randint(0, 10, (4, 6, 8)) # row의 개수가 6개, column의 개수가 8개라서 6*8 matrix를 담는 배열이다.
print(arr)



[[[6 8 8 8 3 3 4 3]
  [5 0 2 9 1 5 0 3]
  [0 0 2 8 5 9 5 1]
  [5 1 8 4 5 0 9 2]
  [3 4 3 5 7 1 4 0]
  [6 6 0 3 7 2 4 6]]

 [[8 0 6 9 4 8 9 5]
  [1 6 0 7 8 3 2 9]
  [6 2 9 1 1 1 9 1]
  [6 9 0 4 0 4 0 8]
  [6 4 4 0 5 4 9 1]
  [5 9 8 3 2 1 7 3]]

 [[2 0 5 0 8 9 0 9]
  [7 5 1 5 2 5 7 0]
  [3 4 2 9 4 6 9 0]
  [9 0 9 7 3 2 5 1]
  [8 3 3 8 5 0 8 3]
  [7 5 7 3 0 4 8 8]]

 [[9 7 6 6 3 5 0 8]
  [6 4 8 0 4 7 4 8]
  [7 9 2 5 5 7 5 0]
  [3 2 6 7 2 3 1 2]
  [3 4 3 0 7 0 5 2]
  [1 6 2 8 3 3 1 9]]]


In [53]:

print(arr[0])
print(arr[0].shape) # (6, 8)

[[6 8 8 8 3 3 4 3]
 [5 0 2 9 1 5 0 3]
 [0 0 2 8 5 9 5 1]
 [5 1 8 4 5 0 9 2]
 [3 4 3 5 7 1 4 0]
 [6 6 0 3 7 2 4 6]]
(6, 8)


In [54]:

arr_vsplit = np.vsplit(arr, 2) # axis = 0
print(arr_vsplit)

[array([[[6, 8, 8, 8, 3, 3, 4, 3],
        [5, 0, 2, 9, 1, 5, 0, 3],
        [0, 0, 2, 8, 5, 9, 5, 1],
        [5, 1, 8, 4, 5, 0, 9, 2],
        [3, 4, 3, 5, 7, 1, 4, 0],
        [6, 6, 0, 3, 7, 2, 4, 6]],

       [[8, 0, 6, 9, 4, 8, 9, 5],
        [1, 6, 0, 7, 8, 3, 2, 9],
        [6, 2, 9, 1, 1, 1, 9, 1],
        [6, 9, 0, 4, 0, 4, 0, 8],
        [6, 4, 4, 0, 5, 4, 9, 1],
        [5, 9, 8, 3, 2, 1, 7, 3]]]), array([[[2, 0, 5, 0, 8, 9, 0, 9],
        [7, 5, 1, 5, 2, 5, 7, 0],
        [3, 4, 2, 9, 4, 6, 9, 0],
        [9, 0, 9, 7, 3, 2, 5, 1],
        [8, 3, 3, 8, 5, 0, 8, 3],
        [7, 5, 7, 3, 0, 4, 8, 8]],

       [[9, 7, 6, 6, 3, 5, 0, 8],
        [6, 4, 8, 0, 4, 7, 4, 8],
        [7, 9, 2, 5, 5, 7, 5, 0],
        [3, 2, 6, 7, 2, 3, 1, 2],
        [3, 4, 3, 0, 7, 0, 5, 2],
        [1, 6, 2, 8, 3, 3, 1, 9]]])]


In [56]:
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit) # axis = 1


[array([[[6, 8, 8, 8, 3, 3, 4, 3],
        [5, 0, 2, 9, 1, 5, 0, 3],
        [0, 0, 2, 8, 5, 9, 5, 1]],

       [[8, 0, 6, 9, 4, 8, 9, 5],
        [1, 6, 0, 7, 8, 3, 2, 9],
        [6, 2, 9, 1, 1, 1, 9, 1]],

       [[2, 0, 5, 0, 8, 9, 0, 9],
        [7, 5, 1, 5, 2, 5, 7, 0],
        [3, 4, 2, 9, 4, 6, 9, 0]],

       [[9, 7, 6, 6, 3, 5, 0, 8],
        [6, 4, 8, 0, 4, 7, 4, 8],
        [7, 9, 2, 5, 5, 7, 5, 0]]]), array([[[5, 1, 8, 4, 5, 0, 9, 2],
        [3, 4, 3, 5, 7, 1, 4, 0],
        [6, 6, 0, 3, 7, 2, 4, 6]],

       [[6, 9, 0, 4, 0, 4, 0, 8],
        [6, 4, 4, 0, 5, 4, 9, 1],
        [5, 9, 8, 3, 2, 1, 7, 3]],

       [[9, 0, 9, 7, 3, 2, 5, 1],
        [8, 3, 3, 8, 5, 0, 8, 3],
        [7, 5, 7, 3, 0, 4, 8, 8]],

       [[3, 2, 6, 7, 2, 3, 1, 2],
        [3, 4, 3, 0, 7, 0, 5, 2],
        [1, 6, 2, 8, 3, 3, 1, 9]]])]


h, v 따로 외우는 것보단 np.split(), np.concatenate()의 매개변수를 바꾸는 것이 낫다.<br>
np.split(ndarray, sections: int, axis=0) <br>
ndarray를 sections(정수)만큼 axis를 기준으로 나눈다.

In [58]:
arr = np.random.randint(0, 10, (4, 6, 8))
arr1 = np.split(arr, 2, axis=0)
print(arr1)

[array([[[5, 5, 8, 3, 8, 5, 9, 9],
        [9, 3, 6, 0, 9, 5, 9, 5],
        [1, 6, 5, 6, 2, 2, 7, 9],
        [9, 5, 9, 6, 6, 3, 2, 4],
        [9, 4, 7, 3, 9, 2, 5, 3],
        [6, 5, 3, 0, 2, 2, 2, 7]],

       [[3, 4, 3, 0, 5, 4, 4, 3],
        [8, 5, 5, 4, 0, 1, 8, 2],
        [4, 1, 4, 4, 7, 1, 9, 8],
        [5, 5, 9, 1, 6, 8, 8, 7],
        [8, 9, 4, 6, 4, 0, 6, 6],
        [4, 0, 4, 7, 8, 8, 9, 9]]]), array([[[3, 4, 8, 3, 9, 8, 6, 6],
        [7, 9, 3, 3, 5, 7, 5, 8],
        [2, 1, 4, 4, 7, 1, 7, 3],
        [3, 7, 2, 7, 6, 5, 7, 9],
        [6, 0, 0, 9, 9, 0, 7, 2],
        [0, 0, 0, 5, 0, 4, 7, 8]],

       [[6, 8, 0, 8, 8, 1, 9, 3],
        [1, 0, 3, 7, 9, 5, 5, 7],
        [4, 8, 1, 7, 1, 5, 9, 3],
        [4, 9, 7, 5, 5, 6, 4, 2],
        [5, 7, 0, 1, 8, 8, 2, 5],
        [3, 0, 6, 0, 8, 0, 5, 2]]])]


In [59]:
arr2 = np.split(arr, 2, axis=1)
print(arr2)

[array([[[5, 5, 8, 3, 8, 5, 9, 9],
        [9, 3, 6, 0, 9, 5, 9, 5],
        [1, 6, 5, 6, 2, 2, 7, 9]],

       [[3, 4, 3, 0, 5, 4, 4, 3],
        [8, 5, 5, 4, 0, 1, 8, 2],
        [4, 1, 4, 4, 7, 1, 9, 8]],

       [[3, 4, 8, 3, 9, 8, 6, 6],
        [7, 9, 3, 3, 5, 7, 5, 8],
        [2, 1, 4, 4, 7, 1, 7, 3]],

       [[6, 8, 0, 8, 8, 1, 9, 3],
        [1, 0, 3, 7, 9, 5, 5, 7],
        [4, 8, 1, 7, 1, 5, 9, 3]]]), array([[[9, 5, 9, 6, 6, 3, 2, 4],
        [9, 4, 7, 3, 9, 2, 5, 3],
        [6, 5, 3, 0, 2, 2, 2, 7]],

       [[5, 5, 9, 1, 6, 8, 8, 7],
        [8, 9, 4, 6, 4, 0, 6, 6],
        [4, 0, 4, 7, 8, 8, 9, 9]],

       [[3, 7, 2, 7, 6, 5, 7, 9],
        [6, 0, 0, 9, 9, 0, 7, 2],
        [0, 0, 0, 5, 0, 4, 7, 8]],

       [[4, 9, 7, 5, 5, 6, 4, 2],
        [5, 7, 0, 1, 8, 8, 2, 5],
        [3, 0, 6, 0, 8, 0, 5, 2]]])]


In [60]:
arr3 = np.split(arr, 2, axis=2)
print(arr3)

[array([[[5, 5, 8, 3],
        [9, 3, 6, 0],
        [1, 6, 5, 6],
        [9, 5, 9, 6],
        [9, 4, 7, 3],
        [6, 5, 3, 0]],

       [[3, 4, 3, 0],
        [8, 5, 5, 4],
        [4, 1, 4, 4],
        [5, 5, 9, 1],
        [8, 9, 4, 6],
        [4, 0, 4, 7]],

       [[3, 4, 8, 3],
        [7, 9, 3, 3],
        [2, 1, 4, 4],
        [3, 7, 2, 7],
        [6, 0, 0, 9],
        [0, 0, 0, 5]],

       [[6, 8, 0, 8],
        [1, 0, 3, 7],
        [4, 8, 1, 7],
        [4, 9, 7, 5],
        [5, 7, 0, 1],
        [3, 0, 6, 0]]]), array([[[8, 5, 9, 9],
        [9, 5, 9, 5],
        [2, 2, 7, 9],
        [6, 3, 2, 4],
        [9, 2, 5, 3],
        [2, 2, 2, 7]],

       [[5, 4, 4, 3],
        [0, 1, 8, 2],
        [7, 1, 9, 8],
        [6, 8, 8, 7],
        [4, 0, 6, 6],
        [8, 8, 9, 9]],

       [[9, 8, 6, 6],
        [5, 7, 5, 8],
        [7, 1, 7, 3],
        [6, 5, 7, 9],
        [9, 0, 7, 2],
        [0, 4, 7, 8]],

       [[8, 1, 9, 3],
        [9, 5, 5, 7],
        [1, 5, 9

In [62]:
# 3차원 행렬 붙이기
arr1 = np.random.randint(1, 10, (3,3,3))
arr2 = np.random.randint(1, 10, (3,3,3))
arr3 = np.concatenate([arr1, arr2], axis=2)
print(arr3)

[[[1 7 3 3 9 3]
  [5 4 6 6 6 5]
  [2 8 3 4 6 8]]

 [[3 9 9 9 4 1]
  [5 9 6 3 4 9]
  [1 1 1 3 9 4]]

 [[4 1 2 6 8 6]
  [3 8 4 3 1 6]
  [3 1 4 4 8 1]]]
