np.sort(ndarray, axis: int | None)
np.argsort(ndarray, axis: int | None)

In [19]:
import numpy as np

arr = np.random.randint(low=0, high=10, size=10)
print(arr)

[8 5 5 6 6 7 3 0 7 1]


In [20]:
arr2 = np.sort(arr) # (ndarray) -> ndarray
print(arr) # 원본은 그대로
print(arr2) # 디폴트 오름차순
print(np.sort(arr)[::-1]) # 내림차순


[8 5 5 6 6 7 3 0 7 1]
[0 1 3 5 5 6 6 7 7 8]
[8 7 7 6 6 5 5 3 1 0]


In [21]:
print(arr)
arr.sort()
print(arr)
# C++ 함수형식과 객체지향 메소드의 차이이다.
# 함수의 새 봔환값과 본체가 바뀐다.

[8 5 5 6 6 7 3 0 7 1]
[0 1 3 5 5 6 6 7 7 8]


In [22]:
# 2차원배열
arr = np.random.randint(0, 15, size=(3,4))
print(arr)

[[ 4  3  6 11]
 [10  5 13  2]
 [ 5  1 13  2]]


In [23]:
print(np.sort(arr)) # default axis=1
print(np.sort(arr, axis=0))

[[ 3  4  6 11]
 [ 2  5 10 13]
 [ 1  2  5 13]]
[[ 4  1  6  2]
 [ 5  3 13  2]
 [10  5 13 11]]


In [24]:
print(np.sort(arr, axis= None)) # 2차원 -> 1차원 배열로 바꾸어 다 정렬함

[ 1  2  2  3  4  5  5  6 10 11 13 13]


In [27]:
# argsort() : 원래 배열을 정렬한 뒤에 그 값의 원래 위치 index를 배열에 담는다.
print(np.sort(arr, axis=1))
print(np.argsort(arr, axis=1))
print(np.argsort(arr, axis=0)) # axis=0을 기준으로 index를 책정했다.
print(np.argsort(arr, axis=None))

[[ 3  4  6 11]
 [ 2  5 10 13]
 [ 1  2  5 13]]
[[1 0 2 3]
 [3 1 0 2]
 [1 3 0 2]]
[[0 2 0 1]
 [2 0 1 2]
 [1 1 2 0]]
[ 9  7 11  1  0  5  8  2  4  3  6 10]
