In [2]:
import numpy as np
# 1차원 배열 인덱스 접근
arr = np.arange(0, 10)

print(arr)
print(arr[3])
print(arr[-1]) # 파이썬처럼 접근 가능하다.

[0 1 2 3 4 5 6 7 8 9]
3
9


In [3]:
# 2차원 배열
# aragne == array_range
arr = np.array([range(1,5), range(5, 9), range(9, 13)])
arr2 = np.array([np.arange(1,5), np.arange(5, 9), np.arange(9, 13)])
print(arr, arr.shape, arr.ndim, sep='\n')
print(arr2, arr2.shape, arr2.ndim, sep='\n')

print(arr[0], "row 0 list")
print(arr[0][3], "(0, 3) value")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
[1 2 3 4] row 0 list
4 (0, 3) value


In [4]:
arr = np.arange(0, 10)
print(arr[3:8]) # python slicing operation
print(arr[3::2])

[3 4 5 6 7]
[3 5 7 9]


In [5]:
arr = np.array([range(1,5), range(5, 9), range(9, 13)])

print(arr[0, :]) # 0행, 모든 열
print(arr[1:3, ::2]) # 1-2행, 모든 열에서 2칸씩 띄우기

[1 2 3 4]
[[ 5  7]
 [ 9 11]]


In [6]:
# Fancy indexing: 특정 인덱스를 여러개 선택해서 탐색하는 방법

# 1 차원
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0, 2, 4]]) # ndarray[]에 index를 담은 리스트를 넣는다.

[ 5 15 25]


In [7]:
# 2차원
arr = np.array([np.arange(5,21,5), np.arange(25, 41, 5), np.arange(45, 61, 5)])
print(arr)

print(arr[[0, 2], 2:]) 
print(arr[1:, [2, 3]])
"""
ndarray[0축, 1축]
[0, 2] 0행과 2행,  2: 2열부터 끝까지 출력


"""

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[15 20]
 [55 60]]
[[35 40]
 [55 60]]


'\nndarray[0축, 1축]\n[0, 2] 0행과 2행,  2: 2열부터 끝까지 출력\n\n\n'

In [8]:
# boolean indexing: 참거짓으로 탐색함

arr = np.array([1, 2, 3, 4])
print(arr[[True, False, True, True]])

arr = np.array([np.arange(1, 5), np.arange(5, 9)])
print(arr)
print(arr[[True, False], True])

[1 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]


In [9]:
# 조건 연산자로 가져오기

print(arr[arr > 4])
print(arr[arr <= 2])

[5 6 7 8]
[1 2]


In [10]:
arr = np.array(["12", "this", 'name'], dtype=str)
print(arr[[x for x, v in enumerate(arr) if len(v) >2]], arr.ndim, sep='\n')
print(dir(arr[0]), arr[0].size, sep='\n')

['this' 'name']
1
['T', '__abs__', '__add__', '__and__', '__array__', '__array_interface__', '__array_priority__', '__array_struct__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__int__', '__invert__', '__iter__', '__le__', '__len__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__xor__', 'all', 'any', 'argmax', 'argmin', 'argsort', 

Boolean indexing:
numpy.array에 Boolean 연산자를 쓰면 각 요소에 참거짓을 담은 배열이 반환된다.

In [26]:
arr = np.array([[1,2], [3,4]])
print(arr > 2)
print(type(arr > 2))

[[False False]
 [ True  True]]
<class 'numpy.ndarray'>


Fancy indexing:
numpy.array의 index로 index를 표시하는 int, boolean 값을 넣어 특정 요소만 선택할 수 있다.

In [17]:
print(arr[[1], [True, False]]) # [0 axis, 1 axis] == [1, 0]

[3]


둘을 동시에 사용하자. <br>
Boolean indexing -> Fancy indexing <br>
이 순서대로 사용하면 된다. <br>

In [27]:
print(arr[arr[:][1] > 1, [1]])
# Boolean indexing이 넘파이배열을 반환하기 때문에 바로 팬시 인덱싱에 넣을 수 있다.

[2 4]
